export type CrmInteraction = {
  id: string;
  subscriptionId: string;
  customerId: string;
  interactionType: string;
  channel: string;
  initiatedBy: string;
  interactionDate: string;
  notes: string;
  outcome: string;
  attachments?: string | null; // JSON string from backend
  duration?: number | null;
  createdAt: string;

  user?: { id: string; firstName: string; lastName: string };
  subscription?: { id: string; subscriptionNumber: string; crmStatus: string; priority: string };
  customer?: { id: string; customerCode: string; businessName?: string | null; contactPerson?: string | null; phone: string };
};

export type CreateCrmInteractionRequest = {
  subscriptionId: string;
  customerId: string;
  interactionType: string;
  channel: string;
  notes: string;
  outcome: string;
  attachments?: string[];
  durationMinutes?: number;
};

export type CrmFollowUpTask = {
  id: string;
  subscriptionId: string;
  customerId: string;
  assignedTo: string;
  title: string;
  description?: string | null;
  dueDate: string;
  completedDate?: string | null;
  status: string;
  priority: string;
  isAutoGenerated: boolean;
  completionInteractionId?: string | null;
  notes?: string | null;
  createdBy: string;
  createdAt: string;
  updatedAt: string;

  assignedUser?: { id: string; firstName: string; lastName: string };
  creator?: { id: string; firstName: string; lastName: string };
  customer?: { id: string; businessName?: string | null; contactPerson?: string | null; phone: string };
  subscription?: { id: string; subscriptionNumber: string; crmStatus: string; priority: string; accountOwnerId?: string | null; nextFollowUpDate?: string | null };
};

export type CreateFollowUpRequest = {
  subscriptionId: string;
  customerId: string;
  assignedTo: string;
  title: string;
  description?: string;
  dueDate: string;
  priority?: string;
  notes?: string;
  isAutoGenerated?: boolean;
};

export type CompleteFollowUpRequest = {
  interactionType: string;
  channel: string;
  notes: string;
  outcome: string;
  attachments?: string[];
  durationMinutes?: number;
  nextFollowUpDateOverride?: string;
};

export type CrmAlert = {
  id: string;
  alertType: string;
  severity: string;
  customerId: string;
  subscriptionId?: string | null;
  title: string;
  description: string;
  sourceType?: string | null;
  sourceId?: string | null;
  acknowledged: boolean;
  acknowledgedBy?: string | null;
  acknowledgedAt?: string | null;
  resolved: boolean;
  resolvedBy?: string | null;
  resolvedAt?: string | null;
  resolutionNotes?: string | null;
  assignedTo?: string | null;
  assignedAt?: string | null;
  createdAt: string;
  updatedAt: string;
};

export type CrmMyDashboard = {
  windowDays: number;
  inactivityDays: number;
  queues: {
    dueToday: CrmFollowUpTask[];
    overdue: CrmFollowUpTask[];
    upcoming: CrmFollowUpTask[];
  };
  recentlyContacted: any[];
  inactiveSubscriptions: any[];
};

export type CrmManagerDashboard = {
  windowDays: number;
  inactivityDays: number;
  followUps: {
    dueToday: number;
    completedToday: number;
    completionRate: number;
  };
  interactionPerUser: { userId: string; userName: string; count: number }[];
  inactiveSubscriptions: any[];
  feedbackAttentionLast30Days: number;
  tickets: { openTickets: number; slaBreachedTickets: number };
};
