import { useEffect, useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { subscriptionsService } from "@/api/services/subscriptions.service";
import { useAuth } from "@/contexts/AuthContext";
import { Textarea } from "@/components/ui/textarea";
import { Checkbox } from "@/components/ui/checkbox";
import {
  Select, SelectContent, SelectItem, SelectTrigger, SelectValue
} from "@/components/ui/select";

function toDatetimeLocalValue(d: Date) {
  const pad = (n: number) => String(n).padStart(2, "0");
  const yyyy = d.getFullYear();
  const mm = pad(d.getMonth() + 1);
  const dd = pad(d.getDate());
  const hh = pad(d.getHours());
  const mi = pad(d.getMinutes());
  return `${yyyy}-${mm}-${dd}T${hh}:${mi}`;
}

type Props = {
  open: boolean;
  onOpenChange: (v: boolean) => void;
  onSubmit: (payload: any) => Promise<void>;
  loading?: boolean;
  subscriptionIdPreset?: string;
};

export default function CreateFollowUpDialog({
  open,
  onOpenChange,
  onSubmit,
  loading,
  subscriptionIdPreset,
}: Props) {
  const { user } = useAuth();

  const [searchSub, setSearchSub] = useState("");
  const [selectedSubscriptionId, setSelectedSubscriptionId] = useState<string>(subscriptionIdPreset || "");
  const [title, setTitle] = useState("Follow-up");
  const [description, setDescription] = useState("");
  const [priority, setPriority] = useState<"LOW" | "NORMAL" | "HIGH" | "CRITICAL">("NORMAL");
  const [dueDateLocal, setDueDateLocal] = useState<string>(toDatetimeLocalValue(new Date(Date.now() + 60 * 60 * 1000)));
  const [assignToOwner, setAssignToOwner] = useState(true);

  // If no preset subscription, let user search subscriptions (billing endpoint)
  const subsQuery = useQuery({
    queryKey: ["subs-search-for-followup", searchSub],
    queryFn: () => subscriptionsService.getAll(1, 25, searchSub),
    enabled: open && !subscriptionIdPreset,
  });

  // Load selected subscription details to auto-derive customerId and ownerId
  const subscriptionQuery = useQuery({
    queryKey: ["subscription-for-followup", selectedSubscriptionId],
    queryFn: () => subscriptionsService.getById(selectedSubscriptionId),
    enabled: open && !!selectedSubscriptionId,
  });

  const subscription: any = subscriptionQuery.data;

  useEffect(() => {
    if (!open) return;
    if (subscriptionIdPreset) setSelectedSubscriptionId(subscriptionIdPreset);
  }, [open, subscriptionIdPreset]);

  const customerId = subscription?.customerId || "";
  const ownerId = subscription?.accountOwnerId || "";

  const assignedTo = useMemo(() => {
    if (assignToOwner && ownerId) return ownerId;
    return user?.id || "";
  }, [assignToOwner, ownerId, user?.id]);

  const submit = async () => {
    // Server expects ISO date string in dto.dueDate
    const dueDateIso = new Date(dueDateLocal).toISOString();

    await onSubmit({
      subscriptionId: selectedSubscriptionId,
      customerId,
      assignedTo,
      title,
      description: description || undefined,
      dueDate: dueDateIso,
      priority,
      isAutoGenerated: false,
    });
  };

  const canSubmit =
    !!selectedSubscriptionId &&
    !!customerId &&
    !!assignedTo &&
    !!title.trim() &&
    !!dueDateLocal;

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-xl">
        <DialogHeader>
          <DialogTitle>Create Follow-up</DialogTitle>
        </DialogHeader>

        <div className="space-y-4">
          {!subscriptionIdPreset && (
            <div className="space-y-2">
              <div className="text-sm font-medium">Find Subscription</div>
              <Input
                placeholder="Search by subscription/customer/product/IMEI..."
                value={searchSub}
                onChange={(e) => setSearchSub(e.target.value)}
              />
              <div className="border rounded-md max-h-40 overflow-y-auto">
                {subsQuery.isLoading ? (
                  <div className="p-3 text-sm text-muted-foreground">Searching...</div>
                ) : (
                  (subsQuery.data?.data || []).map((s: any) => (
                    <button
                      key={s.id}
                      type="button"
                      className={`w-full text-left p-3 hover:bg-accent/50 border-b last:border-b-0 ${
                        selectedSubscriptionId === s.id ? "bg-accent/30" : ""
                      }`}
                      onClick={() => setSelectedSubscriptionId(s.id)}
                    >
                      <div className="font-mono text-sm font-semibold">{s.subscriptionNumber}</div>
                      <div className="text-xs text-muted-foreground">
                        {s.customer?.businessName || s.customer?.contactPerson} • {s.product?.name}
                      </div>
                    </button>
                  ))
                )}
                {!subsQuery.isLoading && (subsQuery.data?.data || []).length === 0 && (
                  <div className="p-3 text-sm text-muted-foreground">No results</div>
                )}
              </div>
            </div>
          )}

          {!!selectedSubscriptionId && (
            <div className="p-3 rounded-md border bg-muted/30">
              <div className="text-xs text-muted-foreground">Selected subscription</div>
              <div className="font-mono font-semibold">{subscription?.subscriptionNumber || selectedSubscriptionId}</div>
              <div className="text-xs text-muted-foreground">
                {subscription?.customer?.businessName || subscription?.customer?.contactPerson || "—"} •{" "}
                {subscription?.product?.name || "—"}
              </div>
            </div>
          )}

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            <div className="sm:col-span-2">
              <div className="text-sm font-medium mb-1">Title</div>
              <Input value={title} onChange={(e) => setTitle(e.target.value)} />
            </div>

            <div>
              <div className="text-sm font-medium mb-1">Due date/time</div>
              <Input
                type="datetime-local"
                value={dueDateLocal}
                onChange={(e) => setDueDateLocal(e.target.value)}
              />
              <div className="text-xs text-muted-foreground mt-1">
                Uses your browser timezone; backend stores ISO/UTC.
              </div>
            </div>

            <div>
              <div className="text-sm font-medium mb-1">Priority</div>
              <Select value={priority} onValueChange={(v: any) => setPriority(v)}>
                <SelectTrigger><SelectValue /></SelectTrigger>
                <SelectContent>
                  <SelectItem value="LOW">LOW</SelectItem>
                  <SelectItem value="NORMAL">NORMAL</SelectItem>
                  <SelectItem value="HIGH">HIGH</SelectItem>
                  <SelectItem value="CRITICAL">CRITICAL</SelectItem>
                </SelectContent>
              </Select>
            </div>

            <div className="sm:col-span-2">
              <div className="text-sm font-medium mb-1">Description (optional)</div>
              <Textarea
                value={description}
                onChange={(e) => setDescription(e.target.value)}
                placeholder="What do you want to achieve in this follow-up?"
              />
            </div>

            <div className="sm:col-span-2">
              <label className="flex items-center gap-2 text-sm cursor-pointer">
                <Checkbox checked={assignToOwner} onCheckedChange={(v) => setAssignToOwner(!!v)} />
                Assign to subscription owner (recommended)
              </label>
              <div className="text-xs text-muted-foreground mt-1">
                If no owner exists, it will default to you.
              </div>
            </div>
          </div>

          <div className="flex justify-end gap-2 pt-2">
            <Button variant="outline" onClick={() => onOpenChange(false)}>
              Cancel
            </Button>
            <Button disabled={!!loading || !canSubmit} onClick={submit}>
              {loading ? "Creating..." : "Create Follow-up"}
            </Button>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}
